import type { Questionnaire } from "./questionnaire";

export function makeSampleQuestionnaire(): Questionnaire {
  return {
    consent_self_reported: true,
    primary_contact_name: "Test User",
    primary_contact_email: "test@example.com",
    primary_contact_phone: "01234567890",
    business_name: "Example Business Ltd",
    site_address_line1: "1 Example Street",
    site_postcode: "AB12 3CD",
    sector: "Office",
    employees_on_site: 25,
    days_open_per_week: "5",
    weekly_operational_hours: 45,
    ownership_status: "Owner‑occupier",
    building_type: "Office",
    floor_area_band: "250–500",
    building_age_band: "2001–2015",
    insulation_level: "Average",
    glazing_type: "Double",
    epc_known: "No",
    epc_rating: undefined,
    electricity_kwh_annual: 120000,
    electricity_cost_annual_ex_vat: 42000,
    uses_gas: "No",
    gas_kwh_annual: undefined,
    gas_cost_annual_ex_vat: undefined,
    gas_usage_purpose: undefined,
    other_fuels: "No",
    other_fuels_spend_annual: undefined,
    has_lighting: "Yes",
    has_space_heating: "Yes",
    has_boiler: "No",
    has_heat_pump: "No",
    uses_electric_heaters: "No",
    has_cooling: "Yes",
    has_ventilation: "Yes",
    has_refrigeration: "Yes",
    has_process_loads: "Yes",
    consider_solar_pv: "Yes",
    lighting_type: "Mostly LED",
    lighting_controls: ["Manual switches only"],
    low_occupancy_areas_left_on: "No",
    heating_main_type: "Gas boiler",
    heating_controls: ["Programmable timer"],
    heating_age_band: "5–10",
    heating_common_issues: "No issues/Unsure",
    boiler_fuel: undefined,
    boiler_age_band: undefined,
    boiler_controls: undefined,
    electric_heaters_type: undefined,
    electric_heaters_frequency: undefined,
    cooling_type: "Split AC",
    cooling_usage: "Some days",
    cooling_age_band: "5–10",
    ventilation_schedule: "Only during opening hours",
    ventilation_controls: "Timer/scheduled",
    heat_recovery_present: "No",
    refrigeration_types: ["Display fridges"],
    refrigeration_count_band: "3–5",
    refrigeration_24_7: "Yes",
    process_load_types: ["Catering equipment"],
    process_load_intensity: "Medium",
    roof_control_permission: "Yes",
    roof_type: "Pitched",
    roof_area_band: "150–300m²",
    roof_shading: "Some",
    primary_priority: "Balanced",
    budget_band: "£5–25k",
    implementation_timeframe: "3–12 months",
    other_major_energy_users: "No",
    other_major_energy_users_desc: undefined,
  };
}

